
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ucelik
 */
public class TurEngSozluk extends javax.swing.JFrame {

  /**
   * Creates new form TurEngSozluk
   */
  public TurEngSozluk() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTabbedPane2 = new javax.swing.JTabbedPane();
    jPanel_KAYDET = new javax.swing.JPanel();
    jLabel_TURKCE = new javax.swing.JLabel();
    jTextField_TURKCE = new javax.swing.JTextField();
    jLabel_ENGLISH = new javax.swing.JLabel();
    jTextField_ENGLISH = new javax.swing.JTextField();
    jButton_KAYDET = new javax.swing.JButton();
    jPanel_LISTELE = new javax.swing.JPanel();
    jButton_LISTELE = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea_LISTE = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Türkçe İngilizce Sözlük");

    jPanel_KAYDET.setBackground(new java.awt.Color(153, 255, 204));

    jLabel_TURKCE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel_TURKCE.setText("TÜRKÇE");

    jTextField_TURKCE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

    jLabel_ENGLISH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel_ENGLISH.setText("ENGLISH");

    jTextField_ENGLISH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

    jButton_KAYDET.setBackground(new java.awt.Color(255, 153, 153));
    jButton_KAYDET.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jButton_KAYDET.setText("KAYDET");
    jButton_KAYDET.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton_KAYDETActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel_KAYDETLayout = new javax.swing.GroupLayout(jPanel_KAYDET);
    jPanel_KAYDET.setLayout(jPanel_KAYDETLayout);
    jPanel_KAYDETLayout.setHorizontalGroup(
      jPanel_KAYDETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_KAYDETLayout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addGroup(jPanel_KAYDETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel_TURKCE, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel_ENGLISH))
        .addGap(18, 18, 18)
        .addGroup(jPanel_KAYDETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButton_KAYDET, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
          .addComponent(jTextField_TURKCE, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jTextField_ENGLISH))
        .addContainerGap())
    );
    jPanel_KAYDETLayout.setVerticalGroup(
      jPanel_KAYDETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_KAYDETLayout.createSequentialGroup()
        .addGap(24, 24, 24)
        .addGroup(jPanel_KAYDETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel_TURKCE, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jTextField_TURKCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel_KAYDETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel_ENGLISH)
          .addComponent(jTextField_ENGLISH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jButton_KAYDET)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jTabbedPane2.addTab("KAYDET", jPanel_KAYDET);

    jPanel_LISTELE.setBackground(new java.awt.Color(255, 255, 204));

    jButton_LISTELE.setBackground(new java.awt.Color(51, 51, 255));
    jButton_LISTELE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButton_LISTELE.setText("Kelimeleri Listele");
    jButton_LISTELE.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton_LISTELEActionPerformed(evt);
      }
    });

    jTextArea_LISTE.setColumns(20);
    jTextArea_LISTE.setRows(5);
    jScrollPane1.setViewportView(jTextArea_LISTE);

    javax.swing.GroupLayout jPanel_LISTELELayout = new javax.swing.GroupLayout(jPanel_LISTELE);
    jPanel_LISTELE.setLayout(jPanel_LISTELELayout);
    jPanel_LISTELELayout.setHorizontalGroup(
      jPanel_LISTELELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LISTELELayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel_LISTELELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jScrollPane1)
          .addComponent(jButton_LISTELE, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel_LISTELELayout.setVerticalGroup(
      jPanel_LISTELELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_LISTELELayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jButton_LISTELE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabbedPane2.addTab("LİSTELE", jPanel_LISTELE);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTabbedPane2)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTabbedPane2)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton_KAYDETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_KAYDETActionPerformed
    String adres = "C:\\Users\\ucelik\\Documents\\sozluk.txt";
    String tur = jTextField_TURKCE.getText();
    String eng = jTextField_ENGLISH.getText();    
    try {
      File dosya = new File(adres);
      FileWriter dosyaYazici = new FileWriter(dosya, true);
      BufferedWriter satirYazici = new BufferedWriter(dosyaYazici);
      satirYazici.write(tur + "=" + eng);
      satirYazici.newLine(); // alt satıra geçer
      satirYazici.close();
      JOptionPane.showMessageDialog(null, "Kayıt Başarılı");
    } catch (IOException ex) {
      JOptionPane.showMessageDialog(null, "Bir hata oldu !!!");
    }
  }//GEN-LAST:event_jButton_KAYDETActionPerformed

  private void jButton_LISTELEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LISTELEActionPerformed
    String adres = "C:\\Users\\ucelik\\Documents\\sozluk.txt";
    String kelimeler = "";
    try {
      Scanner okuyucu = new Scanner(new File(adres));
      while(okuyucu.hasNext()) {
        // her bi satırı okuyup kelimeler değişkenine aktarıyoruz
        kelimeler += okuyucu.next() + "\n";
      }
      okuyucu.close();
      jTextArea_LISTE.setText(kelimeler);
    } catch (FileNotFoundException ex) {
      JOptionPane.showMessageDialog(null, "Bir hata oluştu");
    }
    
  }//GEN-LAST:event_jButton_LISTELEActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TurEngSozluk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TurEngSozluk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TurEngSozluk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TurEngSozluk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TurEngSozluk().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton_KAYDET;
  private javax.swing.JButton jButton_LISTELE;
  private javax.swing.JLabel jLabel_ENGLISH;
  private javax.swing.JLabel jLabel_TURKCE;
  private javax.swing.JPanel jPanel_KAYDET;
  private javax.swing.JPanel jPanel_LISTELE;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTabbedPane jTabbedPane2;
  private javax.swing.JTextArea jTextArea_LISTE;
  private javax.swing.JTextField jTextField_ENGLISH;
  private javax.swing.JTextField jTextField_TURKCE;
  // End of variables declaration//GEN-END:variables
}
