
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ucelik
 */
public class TurEngSozluk extends javax.swing.JFrame {

  /**
   * Creates new form TurEngSozluk
   */
  public TurEngSozluk() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup_ARAMA = new javax.swing.ButtonGroup();
    jTabbedPane2 = new javax.swing.JTabbedPane();
    jPanel_KAYDET = new javax.swing.JPanel();
    jLabel_TURKCE = new javax.swing.JLabel();
    jTextField_TURKCE = new javax.swing.JTextField();
    jLabel_ENGLISH = new javax.swing.JLabel();
    jTextField_ENGLISH = new javax.swing.JTextField();
    jButton_KAYDET = new javax.swing.JButton();
    jPanel_LISTELE = new javax.swing.JPanel();
    jButton_LISTELE = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea_LISTE = new javax.swing.JTextArea();
    jPanel_ARAMA = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jTextField_ARAMA = new javax.swing.JTextField();
    jButton_ARAMA = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTextArea_ARAMA = new javax.swing.JTextArea();
    jRadioButton_TUMKELIME = new javax.swing.JRadioButton();
    jRadioButton_ICINDEGECEN = new javax.swing.JRadioButton();
    jPanel_SILME = new javax.swing.JPanel();
    jButton_GUNCELLE = new javax.swing.JButton();
    jButton_SILME = new javax.swing.JButton();
    jScrollPane3 = new javax.swing.JScrollPane();
    jList_SILME = new javax.swing.JList<>();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Türkçe İngilizce Sözlük");

    jPanel_KAYDET.setBackground(new java.awt.Color(153, 255, 204));

    jLabel_TURKCE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel_TURKCE.setText("TÜRKÇE");

    jTextField_TURKCE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

    jLabel_ENGLISH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel_ENGLISH.setText("ENGLISH");

    jTextField_ENGLISH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

    jButton_KAYDET.setBackground(new java.awt.Color(255, 153, 153));
    jButton_KAYDET.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jButton_KAYDET.setText("KAYDET");
    jButton_KAYDET.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton_KAYDETActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel_KAYDETLayout = new javax.swing.GroupLayout(jPanel_KAYDET);
    jPanel_KAYDET.setLayout(jPanel_KAYDETLayout);
    jPanel_KAYDETLayout.setHorizontalGroup(
      jPanel_KAYDETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_KAYDETLayout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addGroup(jPanel_KAYDETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel_TURKCE, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel_ENGLISH))
        .addGap(18, 18, 18)
        .addGroup(jPanel_KAYDETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButton_KAYDET, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
          .addComponent(jTextField_TURKCE, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jTextField_ENGLISH))
        .addContainerGap())
    );
    jPanel_KAYDETLayout.setVerticalGroup(
      jPanel_KAYDETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_KAYDETLayout.createSequentialGroup()
        .addGap(24, 24, 24)
        .addGroup(jPanel_KAYDETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel_TURKCE, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jTextField_TURKCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel_KAYDETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel_ENGLISH)
          .addComponent(jTextField_ENGLISH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jButton_KAYDET)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jTabbedPane2.addTab("KAYDET", jPanel_KAYDET);

    jPanel_LISTELE.setBackground(new java.awt.Color(255, 255, 204));

    jButton_LISTELE.setBackground(new java.awt.Color(51, 51, 255));
    jButton_LISTELE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButton_LISTELE.setText("Kelimeleri Listele");
    jButton_LISTELE.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton_LISTELEActionPerformed(evt);
      }
    });

    jTextArea_LISTE.setColumns(20);
    jTextArea_LISTE.setRows(5);
    jScrollPane1.setViewportView(jTextArea_LISTE);

    javax.swing.GroupLayout jPanel_LISTELELayout = new javax.swing.GroupLayout(jPanel_LISTELE);
    jPanel_LISTELE.setLayout(jPanel_LISTELELayout);
    jPanel_LISTELELayout.setHorizontalGroup(
      jPanel_LISTELELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LISTELELayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel_LISTELELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jScrollPane1)
          .addComponent(jButton_LISTELE, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel_LISTELELayout.setVerticalGroup(
      jPanel_LISTELELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_LISTELELayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jButton_LISTELE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabbedPane2.addTab("LİSTELE", jPanel_LISTELE);

    jPanel_ARAMA.setBackground(new java.awt.Color(204, 204, 255));

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel1.setText("Aranacak kelimeyi giriniz : ");

    jTextField_ARAMA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

    jButton_ARAMA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButton_ARAMA.setText("Kelime Ara");
    jButton_ARAMA.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton_ARAMAActionPerformed(evt);
      }
    });

    jTextArea_ARAMA.setColumns(20);
    jTextArea_ARAMA.setRows(5);
    jScrollPane2.setViewportView(jTextArea_ARAMA);

    buttonGroup_ARAMA.add(jRadioButton_TUMKELIME);
    jRadioButton_TUMKELIME.setSelected(true);
    jRadioButton_TUMKELIME.setText("Tümü");

    buttonGroup_ARAMA.add(jRadioButton_ICINDEGECEN);
    jRadioButton_ICINDEGECEN.setText("İçinde Geçen");

    javax.swing.GroupLayout jPanel_ARAMALayout = new javax.swing.GroupLayout(jPanel_ARAMA);
    jPanel_ARAMA.setLayout(jPanel_ARAMALayout);
    jPanel_ARAMALayout.setHorizontalGroup(
      jPanel_ARAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_ARAMALayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel_ARAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane2)
          .addGroup(jPanel_ARAMALayout.createSequentialGroup()
            .addGroup(jPanel_ARAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jLabel1)
              .addGroup(jPanel_ARAMALayout.createSequentialGroup()
                .addComponent(jRadioButton_TUMKELIME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton_ICINDEGECEN)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel_ARAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jButton_ARAMA, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
              .addComponent(jTextField_ARAMA))))
        .addContainerGap())
    );
    jPanel_ARAMALayout.setVerticalGroup(
      jPanel_ARAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_ARAMALayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel_ARAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(jTextField_ARAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel_ARAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton_ARAMA)
          .addComponent(jRadioButton_TUMKELIME)
          .addComponent(jRadioButton_ICINDEGECEN))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabbedPane2.addTab("ARAMA", jPanel_ARAMA);

    jPanel_SILME.setBackground(new java.awt.Color(255, 204, 204));

    jButton_GUNCELLE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jButton_GUNCELLE.setText("Listeyi Güncelle");
    jButton_GUNCELLE.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton_GUNCELLEActionPerformed(evt);
      }
    });

    jButton_SILME.setBackground(new java.awt.Color(255, 51, 51));
    jButton_SILME.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jButton_SILME.setText("! ! !   S İ L   ! ! !");
    jButton_SILME.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton_SILMEActionPerformed(evt);
      }
    });

    jList_SILME.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jList_SILME.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jList_SILME.setToolTipText("");
    jScrollPane3.setViewportView(jList_SILME);

    javax.swing.GroupLayout jPanel_SILMELayout = new javax.swing.GroupLayout(jPanel_SILME);
    jPanel_SILME.setLayout(jPanel_SILMELayout);
    jPanel_SILMELayout.setHorizontalGroup(
      jPanel_SILMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_SILMELayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel_SILMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane3)
          .addGroup(jPanel_SILMELayout.createSequentialGroup()
            .addComponent(jButton_GUNCELLE)
            .addGap(46, 46, 46)
            .addComponent(jButton_SILME, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 19, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel_SILMELayout.setVerticalGroup(
      jPanel_SILMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_SILMELayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel_SILMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton_GUNCELLE)
          .addComponent(jButton_SILME))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabbedPane2.addTab("SİLME", jPanel_SILME);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTabbedPane2)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTabbedPane2)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton_KAYDETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_KAYDETActionPerformed
    String adres = "C:\\Users\\ucelik\\Documents\\sozluk.txt";
    String tur = jTextField_TURKCE.getText();
    String eng = jTextField_ENGLISH.getText();    
    try {
      File dosya = new File(adres);
      FileWriter dosyaYazici = new FileWriter(dosya, true);
      BufferedWriter satirYazici = new BufferedWriter(dosyaYazici);
      satirYazici.write(tur + "=" + eng);
      satirYazici.newLine(); // alt satıra geçer
      satirYazici.close();
      JOptionPane.showMessageDialog(null, "Kayıt Başarılı");
    } catch (IOException ex) {
      JOptionPane.showMessageDialog(null, "Bir hata oldu !!!");
    }
  }//GEN-LAST:event_jButton_KAYDETActionPerformed

  private void jButton_LISTELEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LISTELEActionPerformed
    String adres = "C:\\Users\\ucelik\\Documents\\sozluk.txt";
    String kelimeler = "";
    try {
      Scanner okuyucu = new Scanner(new File(adres));
      while(okuyucu.hasNext()) {
        // her bi satırı okuyup kelimeler değişkenine aktarıyoruz
        kelimeler += okuyucu.next() + "\n";
      }
      okuyucu.close();
      jTextArea_LISTE.setText(kelimeler);
    } catch (FileNotFoundException ex) {
      JOptionPane.showMessageDialog(null, "Bir hata oluştu");
    }    
  }//GEN-LAST:event_jButton_LISTELEActionPerformed

  private void jButton_ARAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ARAMAActionPerformed
    String adres = "C:\\Users\\ucelik\\Documents\\sozluk.txt";
    String sonuc = "";
    String arananKelime = jTextField_ARAMA.getText();
    String kayit = "";
    String Tur, Eng;
    try {
      Scanner okuyucu = new Scanner(new File(adres));
      while(okuyucu.hasNext()) {
        kayit = okuyucu.next();
        if(jRadioButton_TUMKELIME.isSelected()) {
          Tur = kayit.substring(0, kayit.indexOf("="));
          Eng = kayit.substring(kayit.indexOf("=")+1, kayit.length());
          if(arananKelime.equalsIgnoreCase(Tur)) {
            sonuc += "Aranan : " + arananKelime + " = " + Eng + "\n";
          } else if(arananKelime.equalsIgnoreCase(Eng)) {
            sonuc += "Searched : " + arananKelime + " = " + Tur + "\n";
          }
        } else {
          // içinde geçen kelimeleri alır
          if(kayit.contains(arananKelime)) {
            sonuc += arananKelime + " -> " + kayit + "\n";
          }
        }        
      }
      if(sonuc.equals("")) sonuc = "Aranan kelime bulunamadı";
      jTextArea_ARAMA.setText(sonuc);
    } catch (FileNotFoundException ex) {
      JOptionPane.showMessageDialog(null, "Hata: " + ex.toString());
    }  
  }//GEN-LAST:event_jButton_ARAMAActionPerformed
  
  DefaultListModel dlmSILME = new DefaultListModel();
  private void jButton_GUNCELLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GUNCELLEActionPerformed
    dlmSILME.clear();
    jList_SILME.setModel(dlmSILME);
    String adres = "C:\\Users\\ucelik\\Documents\\sozluk.txt";    
    try {
      Scanner okuyucu = new Scanner(new File(adres));
      while(okuyucu.hasNext()) {
        dlmSILME.addElement(okuyucu.next());
      }
      jList_SILME.setModel(dlmSILME);
      okuyucu.close();
    } catch (FileNotFoundException ex) {
      JOptionPane.showMessageDialog(null, "Hata: " + ex.toString());
    }    
  }//GEN-LAST:event_jButton_GUNCELLEActionPerformed

  private void jButton_SILMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SILMEActionPerformed
    String adres = "C:\\Users\\ucelik\\Documents\\sozluk.txt"; 
    String secilenKelime = jList_SILME.getSelectedValue();
    System.out.println("Seçilen Kelime = " + secilenKelime);
    String kelimeler = "";
    try {
      Scanner okuyucu = new Scanner(new File(adres));
      while(okuyucu.hasNext()) {
        String kayit = okuyucu.next();
        if(!kayit.equals(secilenKelime)) {
          kelimeler += kayit + "\n";
        }
      }
      okuyucu.close();
    } catch (FileNotFoundException ex) {
      JOptionPane.showMessageDialog(null, "Hata: " + ex.toString());
    }
    System.out.println(kelimeler);
    try {
      File dosya = new File(adres);
      FileWriter yazici = new FileWriter(dosya);
      BufferedWriter yaz = new BufferedWriter(yazici);
      yaz.write(kelimeler);
      yaz.newLine();
      yaz.close();
    } catch (IOException ex) {
      JOptionPane.showMessageDialog(null, "Hata: " + ex.toString());
    }
  }//GEN-LAST:event_jButton_SILMEActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TurEngSozluk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TurEngSozluk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TurEngSozluk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TurEngSozluk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TurEngSozluk().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup_ARAMA;
  private javax.swing.JButton jButton_ARAMA;
  private javax.swing.JButton jButton_GUNCELLE;
  private javax.swing.JButton jButton_KAYDET;
  private javax.swing.JButton jButton_LISTELE;
  private javax.swing.JButton jButton_SILME;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel_ENGLISH;
  private javax.swing.JLabel jLabel_TURKCE;
  private javax.swing.JList<String> jList_SILME;
  private javax.swing.JPanel jPanel_ARAMA;
  private javax.swing.JPanel jPanel_KAYDET;
  private javax.swing.JPanel jPanel_LISTELE;
  private javax.swing.JPanel jPanel_SILME;
  private javax.swing.JRadioButton jRadioButton_ICINDEGECEN;
  private javax.swing.JRadioButton jRadioButton_TUMKELIME;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JTabbedPane jTabbedPane2;
  private javax.swing.JTextArea jTextArea_ARAMA;
  private javax.swing.JTextArea jTextArea_LISTE;
  private javax.swing.JTextField jTextField_ARAMA;
  private javax.swing.JTextField jTextField_ENGLISH;
  private javax.swing.JTextField jTextField_TURKCE;
  // End of variables declaration//GEN-END:variables
}
