
import java.awt.Font;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ufukcelik
 */
public class Rehber extends javax.swing.JFrame {
    private Connection conn = null; //Bağlantı nesnemiz
    private String url = "jdbc:derby://localhost:1527/"; //veritabanının adresi ve portu
    private String dbName = "REHBER"; //veritabanının ismi
    private String driver = "org.apache.derby.jdbc.ClientDriver"; // JavaDerby ile Java arasındaki bağlantıyı sağlayan JDBC sürücüsü
    private String userName = "ufuk"; //veritabanı için kullanıcı adı
    private String password = "123"; //kullanıcı şifresi
    private Statement st; // SQL komutumuz için
    private ResultSet res; // sorgulardan dönecek kayıtlar (sonuç kümesi) bu nesne içerisinde tutulacak
    
    /**
     * Creates new form Rehber
     */
    public Rehber() {
        initComponents();
        
        try {
            st = baglantiAc(); // veritabanına bağlanılıyor
            res = st.executeQuery("SELECT * FROM kisi"); // kayıtlar alınıyor
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, "Hata : " + ex.toString());
        }
        
        KayitGetir("ilk");
    }
    public void KayitGetir(String yon) {
        try {
            switch(yon) {
                case "ileri" : res.next(); break;
                case "geri" : res.previous(); break;
                case "ilk" : res.first(); break;
                case "son" : res.last(); break;
                case "mutlak" : res.absolute(Integer.parseInt(jTextField_ID.getText()));
            }
            
            jTextField_AD.setText(res.getString("ad"));
            jTextField_SOYAD.setText(res.getString("soyad"));
            jLabel_YAS.setText("" + res.getInt("yas"));
            jSlider_YAS.setValue(res.getInt("yas"));
            if(res.getInt("cinsiyet") == 0) {
                jRadioButton_ERKEK.setSelected(true);
                jRadioButton_ERKEK.setFont(new Font("Tahoma", Font.BOLD, 13));
                jRadioButton_KADIN.setFont(new Font("Tahoma", Font.PLAIN, 12));
            } else {
                jRadioButton_KADIN.setSelected(true);
                jRadioButton_KADIN.setFont(new java.awt.Font("Tahoma", Font.BOLD, 12)); 
                jRadioButton_ERKEK.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12));
            }   
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Kayıt YOK");
        }
        
    }
    public Statement baglantiAc() throws Exception {
        Class.forName(driver).newInstance();
        conn = DriverManager.getConnection(url + dbName, userName, password);
        return conn.createStatement(
                ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE
        );
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel_KAYITLAR = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_AD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_SOYAD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSlider_YAS = new javax.swing.JSlider();
        jLabel_YAS = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton_ERKEK = new javax.swing.JRadioButton();
        jRadioButton_KADIN = new javax.swing.JRadioButton();
        jPanel_NAVIGASYON = new javax.swing.JPanel();
        jButton_ILK = new javax.swing.JButton();
        jButton_ONCEKI = new javax.swing.JButton();
        jButton_SONRAKI = new javax.swing.JButton();
        jButton_SON = new javax.swing.JButton();
        jPanel_ISLEMLER = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jButton_BUL = new javax.swing.JButton();
        jButton_YENI = new javax.swing.JButton();
        jButton_GUNCELLE = new javax.swing.JButton();
        jButton_EKLE = new javax.swing.JButton();
        jButton_SIL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REHBER");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel_KAYITLAR.setBackground(null);
        jPanel_KAYITLAR.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kayıtlar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel_KAYITLAR.setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel1.setText("AD");

        jLabel2.setText("SOYAD");

        jLabel3.setText("YAŞ");

        jSlider_YAS.setMajorTickSpacing(10);
        jSlider_YAS.setMinorTickSpacing(1);
        jSlider_YAS.setPaintLabels(true);
        jSlider_YAS.setPaintTicks(true);
        jSlider_YAS.setValue(0);
        jSlider_YAS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_YASStateChanged(evt);
            }
        });

        jLabel_YAS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_YAS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_YAS.setText("0");

        jLabel4.setText("CİNSİYET");

        buttonGroup1.add(jRadioButton_ERKEK);
        jRadioButton_ERKEK.setText("Erkek");
        jRadioButton_ERKEK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erkek_Pasif.png"))); // NOI18N
        jRadioButton_ERKEK.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/erkek_Hover.png"))); // NOI18N
        jRadioButton_ERKEK.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/erkek_Secildi.png"))); // NOI18N
        jRadioButton_ERKEK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton_ERKEKStateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButton_KADIN);
        jRadioButton_KADIN.setText("Kadın");
        jRadioButton_KADIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kadin_Pasif.png"))); // NOI18N
        jRadioButton_KADIN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/kadin_Hover.png"))); // NOI18N
        jRadioButton_KADIN.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/kadin_Secildi.png"))); // NOI18N
        jRadioButton_KADIN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton_KADINStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel_KAYITLARLayout = new javax.swing.GroupLayout(jPanel_KAYITLAR);
        jPanel_KAYITLAR.setLayout(jPanel_KAYITLARLayout);
        jPanel_KAYITLARLayout.setHorizontalGroup(
            jPanel_KAYITLARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_KAYITLARLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel_KAYITLARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_KAYITLARLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_ERKEK)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_KADIN))
                    .addGroup(jPanel_KAYITLARLayout.createSequentialGroup()
                        .addGroup(jPanel_KAYITLARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_KAYITLARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                            .addGroup(jPanel_KAYITLARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                .addComponent(jLabel_YAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_KAYITLARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_SOYAD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_AD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider_YAS, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel_KAYITLARLayout.setVerticalGroup(
            jPanel_KAYITLARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_KAYITLARLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel_KAYITLARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_AD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel_KAYITLARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_SOYAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel_KAYITLARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_KAYITLARLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_YAS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_KAYITLARLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSlider_YAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_KAYITLARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel_KAYITLARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton_ERKEK)
                        .addComponent(jRadioButton_KADIN))))
        );

        jPanel_NAVIGASYON.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Navigasyon", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N

        jButton_ILK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_ILK.setText("İLK");
        jButton_ILK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ILKActionPerformed(evt);
            }
        });

        jButton_ONCEKI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_ONCEKI.setText("ÖNCEKİ");
        jButton_ONCEKI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ONCEKIActionPerformed(evt);
            }
        });

        jButton_SONRAKI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_SONRAKI.setText("SONRAKİ");
        jButton_SONRAKI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SONRAKIActionPerformed(evt);
            }
        });

        jButton_SON.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_SON.setText("SON");
        jButton_SON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_NAVIGASYONLayout = new javax.swing.GroupLayout(jPanel_NAVIGASYON);
        jPanel_NAVIGASYON.setLayout(jPanel_NAVIGASYONLayout);
        jPanel_NAVIGASYONLayout.setHorizontalGroup(
            jPanel_NAVIGASYONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NAVIGASYONLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_NAVIGASYONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_ILK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_ONCEKI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_SONRAKI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_SON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_NAVIGASYONLayout.setVerticalGroup(
            jPanel_NAVIGASYONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NAVIGASYONLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton_ILK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_ONCEKI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton_SONRAKI, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_SON, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_ISLEMLER.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "İŞLEMLER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("KAYIT SIRASI");

        jButton_BUL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_BUL.setText("Kayıt Bul");
        jButton_BUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BULActionPerformed(evt);
            }
        });

        jButton_YENI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_YENI.setText("YENİ");
        jButton_YENI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_YENIActionPerformed(evt);
            }
        });

        jButton_GUNCELLE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_GUNCELLE.setText("GÜNCELLE");
        jButton_GUNCELLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GUNCELLEActionPerformed(evt);
            }
        });

        jButton_EKLE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_EKLE.setText("EKLE");
        jButton_EKLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EKLEActionPerformed(evt);
            }
        });

        jButton_SIL.setBackground(new java.awt.Color(255, 51, 51));
        jButton_SIL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_SIL.setForeground(new java.awt.Color(255, 255, 255));
        jButton_SIL.setText("SİL");
        jButton_SIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SILActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ISLEMLERLayout = new javax.swing.GroupLayout(jPanel_ISLEMLER);
        jPanel_ISLEMLER.setLayout(jPanel_ISLEMLERLayout);
        jPanel_ISLEMLERLayout.setHorizontalGroup(
            jPanel_ISLEMLERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ISLEMLERLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ISLEMLERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_YENI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_ISLEMLERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ISLEMLERLayout.createSequentialGroup()
                        .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton_BUL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_ISLEMLERLayout.createSequentialGroup()
                        .addComponent(jButton_GUNCELLE, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_EKLE, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jButton_SIL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_ISLEMLERLayout.setVerticalGroup(
            jPanel_ISLEMLERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ISLEMLERLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ISLEMLERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_BUL))
                .addGap(18, 18, 18)
                .addGroup(jPanel_ISLEMLERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_YENI)
                    .addComponent(jButton_GUNCELLE)
                    .addComponent(jButton_EKLE)
                    .addComponent(jButton_SIL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_ISLEMLER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_KAYITLAR, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel_NAVIGASYON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_NAVIGASYON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_KAYITLAR, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_ISLEMLER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider_YASStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_YASStateChanged
        jLabel_YAS.setText("" + jSlider_YAS.getValue());
    }//GEN-LAST:event_jSlider_YASStateChanged

    private void jRadioButton_ERKEKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton_ERKEKStateChanged
        if(jRadioButton_ERKEK.isSelected()) {
            jRadioButton_ERKEK.setFont(new Font("Tahoma", Font.BOLD, 13));
        } else {
            jRadioButton_ERKEK.setFont(new Font("Tahoma", Font.PLAIN, 12));
        }
    }//GEN-LAST:event_jRadioButton_ERKEKStateChanged

    private void jRadioButton_KADINStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton_KADINStateChanged
        if(jRadioButton_KADIN.isSelected()) {
            jRadioButton_KADIN.setFont(new Font("Tahoma", Font.BOLD, 13));
        } else {
            jRadioButton_KADIN.setFont(new Font("Tahoma", Font.PLAIN, 12));
        }
    }//GEN-LAST:event_jRadioButton_KADINStateChanged

    private void jButton_ILKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ILKActionPerformed
        KayitGetir("ilk");
    }//GEN-LAST:event_jButton_ILKActionPerformed

    private void jButton_ONCEKIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ONCEKIActionPerformed
        KayitGetir("geri");
    }//GEN-LAST:event_jButton_ONCEKIActionPerformed

    private void jButton_SONRAKIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SONRAKIActionPerformed
        KayitGetir("ileri");
    }//GEN-LAST:event_jButton_SONRAKIActionPerformed

    private void jButton_SONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SONActionPerformed
        KayitGetir("son");
    }//GEN-LAST:event_jButton_SONActionPerformed

    private void jButton_BULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BULActionPerformed
        KayitGetir("mutlak");
    }//GEN-LAST:event_jButton_BULActionPerformed

    private void jButton_YENIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_YENIActionPerformed
        jTextField_AD.setText("");
        jTextField_SOYAD.setText("");
        jLabel_YAS.setText("0");
        jSlider_YAS.setValue(0);
        jRadioButton_ERKEK.setSelected(false);
        jRadioButton_ERKEK.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jRadioButton_ERKEK.setIcon(new ImageIcon(getClass().getResource("/erkek_Pasif.png")));
        jRadioButton_KADIN.setSelected(false);
        jRadioButton_KADIN.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jRadioButton_KADIN.setIcon(new ImageIcon(getClass().getResource("kadin_Pasif.png")));
    }//GEN-LAST:event_jButton_YENIActionPerformed

    private void jButton_GUNCELLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GUNCELLEActionPerformed
        try {
            res.updateString("ad", jTextField_AD.getText());
            res.updateString("soyad", jTextField_SOYAD.getText());
            res.updateInt("yas", Integer.parseInt(jLabel_YAS.getText()));
            if(jRadioButton_ERKEK.isSelected()) {
                res.updateInt("cinsiyet", 0);
            } else {
                res.updateInt("cinsiyet", 1);
            }
            res.updateRow();
            JOptionPane.showMessageDialog(null, "Kayıt Güncellendi");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Güncelleme BAŞARISIZ !!!");
        } 
    }//GEN-LAST:event_jButton_GUNCELLEActionPerformed

    private void jButton_EKLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EKLEActionPerformed
        try {
            res.moveToInsertRow(); // Kaydın ekleneceği yeni satıra git
            res.updateString("ad", jTextField_AD.getText());
            res.updateString("soyad", jTextField_SOYAD.getText());
            res.updateInt("yas", Integer.parseInt(jLabel_YAS.getText()));
            if(jRadioButton_ERKEK.isSelected()) {
                res.updateInt("cinsiyet", 0);
            } else {
                res.updateInt("cinsiyet", 1);
            }
            res.insertRow(); // kaydı (satırı) tabloya ekle
            JOptionPane.showMessageDialog(null, "Kayıt eklendi");
            res.close();
            res = st.executeQuery("SELECT * FROM kisi");
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, "Kayıt ekleme BAŞARISIZ !!!");
        }
    }//GEN-LAST:event_jButton_EKLEActionPerformed

    private void jButton_SILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SILActionPerformed
        try {
            int onay = JOptionPane.showConfirmDialog(null, "Emin MİSİNİZ?");
            if(onay == 0) { // yes seçildi
                res.deleteRow();
                KayitGetir("ilk");
                res.close();
                res = st.executeQuery("SELECT * FROM kisi");
            }
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, "Kayıt SİLİNEMEDİ !!!");
        }
    }//GEN-LAST:event_jButton_SILActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try { 
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Rehber.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rehber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rehber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rehber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rehber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rehber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_BUL;
    private javax.swing.JButton jButton_EKLE;
    private javax.swing.JButton jButton_GUNCELLE;
    private javax.swing.JButton jButton_ILK;
    private javax.swing.JButton jButton_ONCEKI;
    private javax.swing.JButton jButton_SIL;
    private javax.swing.JButton jButton_SON;
    private javax.swing.JButton jButton_SONRAKI;
    private javax.swing.JButton jButton_YENI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_YAS;
    private javax.swing.JPanel jPanel_ISLEMLER;
    private javax.swing.JPanel jPanel_KAYITLAR;
    private javax.swing.JPanel jPanel_NAVIGASYON;
    private javax.swing.JRadioButton jRadioButton_ERKEK;
    private javax.swing.JRadioButton jRadioButton_KADIN;
    private javax.swing.JSlider jSlider_YAS;
    private javax.swing.JTextField jTextField_AD;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_SOYAD;
    // End of variables declaration//GEN-END:variables
}
