CREATE table Personel (
    ID INTEGER NOT NULL
        PRIMARY KEY GENERATED 
        ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
    AD VARCHAR(50),
    SOYAD VARCHAR(50),
    YAS SMALLINT,
    CINSIYET VARCHAR(5)
)