
import java.awt.print.PrinterException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ufukcelik
 */
public class JTableBilgiExcel extends javax.swing.JFrame {

    /**
     * Creates new form JTableBilgiExcel
     */
    public JTableBilgiExcel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Excel = new javax.swing.JTable();
        jButton_ExceleAktar = new javax.swing.JButton();
        jButton_YAZDIR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_Excel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"93-3434-3434-12", "Java ile Tasarım", "Turhan ÇOBAN", "Abaküs"},
                {"4545-2323-445-45", "PHP Programlama", "Vehbi GÜNDÜZ", "Pusula"},
                {"34-56-78-2345", "Veri MAdenciliği", "Ayşe CAN, Mehmet KİRAZ", "Beta"},
                {"309798-2334-45656", "Ağ Sistemleri", "Abdullah ÜNAL", "Nobel"}
            },
            new String [] {
                "ISBN", "Kitap Adı", "Yazar", "Yayınevi"
            }
        ));
        jScrollPane1.setViewportView(jTable_Excel);

        jButton_ExceleAktar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_ExceleAktar.setText("Tabloyu Excele Aktar");
        jButton_ExceleAktar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExceleAktarActionPerformed(evt);
            }
        });

        jButton_YAZDIR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_YAZDIR.setText("YAZDIR");
        jButton_YAZDIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_YAZDIRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_ExceleAktar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton_YAZDIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ExceleAktar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_YAZDIR))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ExceleAktarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExceleAktarActionPerformed
        String dosya = System.getProperty("user.dir") + "\\src\\excelDosya.xlsx";
        System.out.println("Dosya yolu : " + dosya);
        Workbook kitap = new XSSFWorkbook();
        Sheet sayfa = kitap.createSheet("JTable Verileri");
        
        TableModel model = jTable_Excel.getModel();
        Row ilkSatir = sayfa.createRow(0);
        Cell baslik1 = ilkSatir.createCell(0,CellType.STRING);
        baslik1.setCellValue("ISBN");
        Cell baslik2 = ilkSatir.createCell(1,CellType.STRING);
        baslik2.setCellValue("KİTAP ADI");
        Cell baslik3 = ilkSatir.createCell(2,CellType.STRING);
        baslik3.setCellValue("YAZAR");
        Cell baslik4 = ilkSatir.createCell(3,CellType.STRING);
        baslik4.setCellValue("YAYINEVİ");

        for(int sat=0; sat<model.getRowCount(); sat++){ // satirlar
            Row satir = sayfa.createRow(sat+1);
            for(int süt=0; süt<model.getColumnCount(); süt++) { // sütunlar
                Cell hucre = satir.createCell(süt, CellType.STRING);
                hucre.setCellValue(model.getValueAt(sat, süt).toString());
            }
        }
        
        try {
            FileOutputStream dosyaVerisi = new FileOutputStream(dosya);
            kitap.write(dosyaVerisi);
            kitap.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JTableBilgiExcel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JTableBilgiExcel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton_ExceleAktarActionPerformed

    private void jButton_YAZDIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_YAZDIRActionPerformed
        try {
            boolean print = jTable_Excel.print();
            JOptionPane.showMessageDialog(this, "Yazdırma İşlemi Başarılı");
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(this, "PROBLEM");
        }
        
    }//GEN-LAST:event_jButton_YAZDIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JTableBilgiExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JTableBilgiExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JTableBilgiExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTableBilgiExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTableBilgiExcel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ExceleAktar;
    private javax.swing.JButton jButton_YAZDIR;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Excel;
    // End of variables declaration//GEN-END:variables
}
