package sirket;




import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ufukcelik
 */
public class UrunKayitForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form UrunKayitForm
     */
    public UrunKayitForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_AD = new javax.swing.JLabel();
        jTextField_AD = new javax.swing.JTextField();
        jLabel_TANIM = new javax.swing.JLabel();
        jScrollPane_TANIM = new javax.swing.JScrollPane();
        jTextArea_TANIM = new javax.swing.JTextArea();
        jLabel_RESIM = new javax.swing.JLabel();
        jButton_KAYDET = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ürün Kayıt Formu");

        jLabel_AD.setText("AD");

        jLabel_TANIM.setText("TANIM");

        jTextArea_TANIM.setColumns(20);
        jTextArea_TANIM.setRows(5);
        jScrollPane_TANIM.setViewportView(jTextArea_TANIM);

        jLabel_RESIM.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_RESIM.setText("Ürün resimi yüklemek için tıklayınız...");
        jLabel_RESIM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_RESIM.setOpaque(true);
        jLabel_RESIM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RESIMMouseClicked(evt);
            }
        });

        jButton_KAYDET.setText("KAYDET");
        jButton_KAYDET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_KAYDETActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_AD)
                    .addComponent(jLabel_TANIM))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_AD)
                    .addComponent(jScrollPane_TANIM)
                    .addComponent(jLabel_RESIM, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(jButton_KAYDET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_AD)
                    .addComponent(jTextField_AD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_TANIM)
                    .addComponent(jScrollPane_TANIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel_RESIM, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_KAYDET, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void jLabel_RESIMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RESIMMouseClicked
        JFileChooser resimSecici = new JFileChooser();
        int secim = resimSecici.showOpenDialog(this);
        if(secim == JFileChooser.APPROVE_OPTION) {
            dosya = resimSecici.getSelectedFile();
            resimAd = dosya.getName();
            resimAdres = dosya.getPath();
            ImageIcon resim = new ImageIcon(resimAdres);
            jLabel_RESIM.setIcon(resim);
            System.out.println("Resim Adı: " + resimAd + 
                    " Resim Adres: " + resimAdres);
            jLabel_RESIM.setText(resimAd);
        }
    }//GEN-LAST:event_jLabel_RESIMMouseClicked
    
    private String resimAd, resimAdres;
    private File dosya;
    
    private void jButton_KAYDETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_KAYDETActionPerformed
        String adres = "jdbc:derby://localhost:1527/SIRKET";
        String kullanici = "ufuk";
        String sifre = "123";
        String AD = jTextField_AD.getText();
        String TANIM = jTextArea_TANIM.getText();
        String sorgu = "INSERT INTO urun(ad,tanim,resimad,resim) VALUES(?,?,?,?)";
        
        try {
            Connection bag = DriverManager.getConnection(adres, kullanici, sifre);
            FileInputStream fis = new FileInputStream(dosya);
            PreparedStatement ps = bag.prepareStatement(sorgu);
            ps.setString(1, AD);
            ps.setString(2, TANIM);
            ps.setString(3, resimAd);
            ps.setBinaryStream(4, fis, (int)dosya.length());
            ps.executeUpdate();
            ps.close(); fis.close(); bag.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Kayıt Yapılamadı.\nSQL Hata: " + ex.toString());
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Dosya Bulunamadı.\nHata:" + ex.toString());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Dosya İşlem Hatası.\nHata:" + ex.toString());
        }
    }//GEN-LAST:event_jButton_KAYDETActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_KAYDET;
    private javax.swing.JLabel jLabel_AD;
    private javax.swing.JLabel jLabel_RESIM;
    private javax.swing.JLabel jLabel_TANIM;
    private javax.swing.JScrollPane jScrollPane_TANIM;
    private javax.swing.JTextArea jTextArea_TANIM;
    private javax.swing.JTextField jTextField_AD;
    // End of variables declaration//GEN-END:variables
}
