
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ufukcelik
 */
public class Personel extends javax.swing.JFrame {
    String adres = "jdbc:derby://localhost:1527/SIRKET";
    String kullanici = "ufuk";
    String sifre = "123";
        
    /**
     * Creates new form Personel
     */
    public Personel() {
        initComponents();
        TabloDoldur();
    }

    public void TabloDoldur() {
        jTable_PERSONEL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "ID", "AD", "SOYAD", "YAŞ", "CİNSİYET"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        try {
            Connection bag = DriverManager.getConnection(adres, kullanici, sifre);
            Statement sorgu = bag.createStatement();
            ResultSet sonuc = sorgu.executeQuery("SELECT * FROM personel");
            int sütun = sonuc.getMetaData().getColumnCount();
            while(sonuc.next()) {
                Object[] satir = new Object[sütun];
                for(int i = 1; i <= sütun; i++) {
                    satir[i - 1] = sonuc.getObject(i);
                }
                ((DefaultTableModel) jTable_PERSONEL.getModel()).insertRow(sonuc.getRow() - 1, satir);
            }
            bag.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Bağlantı Hatası");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_CINSIYET = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_PERSONEL = new javax.swing.JTable();
        jLabel_AD = new javax.swing.JLabel();
        jTextField_AD = new javax.swing.JTextField();
        jLabel_SOYAD = new javax.swing.JLabel();
        jTextField_SOYAD = new javax.swing.JTextField();
        jLabel_YAS = new javax.swing.JLabel();
        jLabel_YasDegeri = new javax.swing.JLabel();
        jSlider_YAS = new javax.swing.JSlider();
        jLabel_CINSIYET = new javax.swing.JLabel();
        jRadioButton_KADIN = new javax.swing.JRadioButton();
        jRadioButton_ERKEK = new javax.swing.JRadioButton();
        jButton_YENI = new javax.swing.JButton();
        jButton_EKLE = new javax.swing.JButton();
        jButton_GUNCELLE = new javax.swing.JButton();
        jButton_SIL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personel");

        jTable_PERSONEL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "AD", "SOYAD", "YAŞ", "CİNSİYET"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_PERSONEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_PERSONELMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_PERSONEL);

        jLabel_AD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_AD.setText("AD");

        jTextField_AD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel_SOYAD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_SOYAD.setText("SOYAD");

        jTextField_SOYAD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel_YAS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_YAS.setText("YAŞ");

        jLabel_YasDegeri.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_YasDegeri.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_YasDegeri.setText("0");

        jSlider_YAS.setMajorTickSpacing(10);
        jSlider_YAS.setMinorTickSpacing(1);
        jSlider_YAS.setPaintLabels(true);
        jSlider_YAS.setPaintTicks(true);
        jSlider_YAS.setValue(0);
        jSlider_YAS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_YASStateChanged(evt);
            }
        });

        jLabel_CINSIYET.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_CINSIYET.setText("CİNSİYET");

        buttonGroup_CINSIYET.add(jRadioButton_KADIN);
        jRadioButton_KADIN.setText("KADIN");
        jRadioButton_KADIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kadin_Pasif.png"))); // NOI18N
        jRadioButton_KADIN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/kadin_Hover.png"))); // NOI18N
        jRadioButton_KADIN.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/kadin_Secildi.png"))); // NOI18N

        buttonGroup_CINSIYET.add(jRadioButton_ERKEK);
        jRadioButton_ERKEK.setText("ERKEK");
        jRadioButton_ERKEK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erkek_Pasif.png"))); // NOI18N
        jRadioButton_ERKEK.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/erkek_Hover.png"))); // NOI18N
        jRadioButton_ERKEK.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/erkek_Secildi.png"))); // NOI18N

        jButton_YENI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_YENI.setText("YENİ");
        jButton_YENI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_YENIActionPerformed(evt);
            }
        });

        jButton_EKLE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_EKLE.setText("EKLE");
        jButton_EKLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EKLEActionPerformed(evt);
            }
        });

        jButton_GUNCELLE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_GUNCELLE.setText("GÜNCELLE");
        jButton_GUNCELLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GUNCELLEActionPerformed(evt);
            }
        });

        jButton_SIL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_SIL.setText("!!! SİL !!!");
        jButton_SIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SILActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_SOYAD)
                                .addComponent(jLabel_YAS)
                                .addComponent(jLabel_YasDegeri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_CINSIYET)
                            .addComponent(jLabel_AD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_SOYAD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider_YAS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton_KADIN)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton_ERKEK))
                            .addComponent(jTextField_AD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_YENI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_SIL, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jButton_GUNCELLE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jButton_EKLE, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_AD)
                    .addComponent(jTextField_AD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_YENI))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_SOYAD)
                    .addComponent(jTextField_SOYAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_EKLE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel_YAS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_YasDegeri, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_CINSIYET))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jSlider_YAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jButton_GUNCELLE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jButton_SIL))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton_KADIN)
                                .addComponent(jRadioButton_ERKEK)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_YENIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_YENIActionPerformed
        jTextField_AD.setText("");
        jTextField_SOYAD.setText("");
        jLabel_YasDegeri.setText("0");
        jSlider_YAS.setValue(0);
        jRadioButton_KADIN.setSelected(false);
        jRadioButton_ERKEK.setSelected(false);
    }//GEN-LAST:event_jButton_YENIActionPerformed

    private void jButton_EKLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EKLEActionPerformed
        String AD = jTextField_AD.getText();
        String SOYAD = jTextField_SOYAD.getText();
        int YAS = jSlider_YAS.getValue();
        String CINSIYET = jRadioButton_KADIN.isSelected() ? "Kadın" : "Erkek";
        String sorgu = "INSERT INTO personel(ad,soyad,yas,cinsiyet) " +
            "VALUES('"+ AD +"','"+ SOYAD +"',"+ YAS +",'"+ CINSIYET +"')";
        
        try {
            Connection bag = DriverManager.getConnection(adres, kullanici, sifre);
            Statement st = bag.createStatement();
            st.executeUpdate(sorgu);
            bag.close();
            TabloDoldur();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Kayıt YAPILMADI");
        }
    }//GEN-LAST:event_jButton_EKLEActionPerformed

    private void jButton_GUNCELLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GUNCELLEActionPerformed
        int secilenSatir = jTable_PERSONEL.getSelectedRow();
        if(secilenSatir == -1) {
            JOptionPane.showMessageDialog(null, "Lütfen bir seçim yapın");
        } else {
            String ID = jTable_PERSONEL.getValueAt(secilenSatir, 0).toString();
            String AD = jTextField_AD.getText();
            String SOYAD = jTextField_SOYAD.getText();
            int YAS = jSlider_YAS.getValue();
            String CINSIYET = jRadioButton_KADIN.isSelected() ? "Kadın" : "Erkek";
            String sorgu = "UPDATE personel SET "
                    + "ad = '" + AD + "', "
                    + "soyad = '" + SOYAD + "', "
                    + "yas = " + YAS + ", "
                    + "cinsiyet = '" + CINSIYET + "' "
                    + "WHERE id = " + ID;
            try {
                Connection bag = DriverManager.getConnection(adres, kullanici, sifre);
                Statement st = bag.createStatement();
                st.executeLargeUpdate(sorgu);
                bag.close();
                TabloDoldur();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Güncelleme HATASI");
            }
        }
    }//GEN-LAST:event_jButton_GUNCELLEActionPerformed

    private void jButton_SILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SILActionPerformed
        int secilenSatir = jTable_PERSONEL.getSelectedRow();
        if(secilenSatir == -1) {
            JOptionPane.showMessageDialog(null, "Lütfen bir seçim yapınız");
        } else {
            int onay = JOptionPane.showConfirmDialog(null, "Emin misiniz?");
            if(onay == 0) { // yes seçildi
                String ID = jTable_PERSONEL.getValueAt(secilenSatir, 0).toString();
                try {
                   Connection bag = DriverManager.getConnection(adres, kullanici, sifre);
                   Statement st = bag.createStatement();
                   st.executeUpdate("DELETE FROM personel WHERE id="+ID);
                   bag.close();
                   TabloDoldur();
                } catch (SQLException ex) {
                    Logger.getLogger(Personel.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        }
    }//GEN-LAST:event_jButton_SILActionPerformed

    private void jTable_PERSONELMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_PERSONELMousePressed
        int secilenSatir = jTable_PERSONEL.getSelectedRow();
        System.out.println("Seçilen Satır = " + secilenSatir);
        String AD = jTable_PERSONEL.getValueAt(secilenSatir, 1).toString();
        String SOYAD = jTable_PERSONEL.getValueAt(secilenSatir, 2).toString();
        String YAS = jTable_PERSONEL.getValueAt(secilenSatir, 3).toString();
        String CINSIYET = jTable_PERSONEL.getValueAt(secilenSatir, 4).toString();
        
        jTextField_AD.setText(AD);
        jTextField_SOYAD.setText(SOYAD);
        jLabel_YasDegeri.setText(YAS);
        jSlider_YAS.setValue(Integer.parseInt(YAS));
        if(CINSIYET.equals("Kadın")) {
            jRadioButton_KADIN.setSelected(true);
        } else {
            jRadioButton_ERKEK.setSelected(true);
        }
    }//GEN-LAST:event_jTable_PERSONELMousePressed

    private void jSlider_YASStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_YASStateChanged
        jLabel_YasDegeri.setText("" + jSlider_YAS.getValue());
    }//GEN-LAST:event_jSlider_YASStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("System".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_CINSIYET;
    private javax.swing.JButton jButton_EKLE;
    private javax.swing.JButton jButton_GUNCELLE;
    private javax.swing.JButton jButton_SIL;
    private javax.swing.JButton jButton_YENI;
    private javax.swing.JLabel jLabel_AD;
    private javax.swing.JLabel jLabel_CINSIYET;
    private javax.swing.JLabel jLabel_SOYAD;
    private javax.swing.JLabel jLabel_YAS;
    private javax.swing.JLabel jLabel_YasDegeri;
    private javax.swing.JRadioButton jRadioButton_ERKEK;
    private javax.swing.JRadioButton jRadioButton_KADIN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider_YAS;
    private javax.swing.JTable jTable_PERSONEL;
    private javax.swing.JTextField jTextField_AD;
    private javax.swing.JTextField jTextField_SOYAD;
    // End of variables declaration//GEN-END:variables
}
